services:
  directory-service-migrations:
    container_name: directory-service-migrations
    build:
      context: ./backend
      dockerfile: DirectoryService/Dockerfile
    entrypoint:
      [
        "/bin/sh",
        "-c",
        './efbundle',
      ]
    depends_on:
      directory-service-postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    restart: "no"
    networks:
      - directory-network
  
  directory-service:
    container_name: directory-service
    build:
      context: ./backend
      dockerfile: DirectoryService/Dockerfile
    ports:
      - "5048:5048"
    depends_on:
      directory-service-postgres:
        condition: service_healthy
      directory-service-migrations:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5048
    restart: always
    networks:
      - directory-network
  
  directory-service-postgres:
    container_name: directory-service-postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: directory_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - directory-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d directory_service_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - directory-network    

networks:
  directory-network:
    external: true

volumes:
  directory-postgres-data: